reference/channels.v3.yml
Adding here for consistency as this enum is already being used in prod. We're rolling out support for Next.js via a Vercel built storefront starter this week.
=> Added next as storefront platform option

reference/settings.v3.yml
This setting will no longer be added to the API under this endpoint. Instead, channel status will be used. So, removing from the spec!
=> Remove status field from storefront settings

reference/marketing.v2.yml
DEVDOCS-2323: While reviewing the changes, I noticed the descriptions were not correct.  Purchase dates are entered in RFC-2822 format and purchase dates are displayed in Unix timestamp format.  I needed to change the wording to convey this difference.
=> DEVDOCS-2323-updated description for purchase_date

models/theme_objects.yml
This lost me about an hour of my day. The example had the type as "imageMaker" instead of the correct "imageManager". Also, seemingly, "default' is a required property but wasn't indicated as such.
=> Fix image manager widget type

reference/shipping_provider.yml
The `handling_fee` object within the Shipping Rate Response is a placeholder for future work and is non-functional.
=> DEVDOCS-2516: Remove Handling Fee

reference/orders.v2.oas2.yml
I was trying to run the Orders V2 schema through [`dtsgenerator`](https://github.com/horiuchi/dtsgenerator) and got the following error:
```
Error: unknown type: float
```
After closer inspection, I think you may have switched the `number` and `float` `type` and `format` respectively.
See [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#dataTypes) for the Open API spec. `float` is not a type.
This fixes the error and allows `dtsgenerator` to work.
---
Hope this helps! I tried to follow PR conventions as much as I could.
=> Fix Incorrect Float Type in Orders V2

reference/.spectral.yml
* Added permanent exceptions for `host:` property in files where the host is not a bigcommerce server.
* Added temporary exceptions for all files with existing errors
This will allow us to use stoplight's spectral github action check pull requests for errors, but make exceptions for existing errors that might not have been a part of the pull request.
=> Add OAS Linting Exceptions

reference/orders.v2.oas2.yml
**1.** Updated the order shipments documentation POST request example and schema body by removing the **product_id** field.
**2.** Updated the order shipments documentation PUT request example and schema body by removing the **items** object.
**1.** When **product_id** field is included in the **POST /orders/{order_id}/shipments request**, users receive the following error:
>"status": 400, "message": "The field 'product_id' cannot be written to. Please remove it from your request before trying again."
When **product_id** field is removed from the request body and all the other fields are valid, a successful response is returned.
**2.** When **items** object is included in the **PUT/orders/{order_id}/shipments/{shipment_id}**, users receive the following error:
>"status": 400, "message": …
=> DEVDOCS-2612 remove unnecessary fields from POST / PUT order shipment request bodies

reference/shipping.v2.yml, reference/shipping.v3.yml
- Update the customs-information documentation PUT request example and schema body
The published documentation is out of date with the usage of the customs-information API. This has caused confusion amongst our API clients who copy and paste the example provided in our dev docs only to be returned with a 500 error. 
ping @bigcommerce/shipping @aglensmith @bigcommerce/dev-docs
=> DEVDOCS-2609 Update customs-information PUT Request example and model

.circleci/config.yml
The new version of spectral (5.9.0) seems to be detecting issues (which appear to be false positives) that the previous version dididn't (5.8.1).  Running the following locally I was able to replicate the errors:
```
npx @stoplight/spectral@5.9.0 lint reference/*.yml -f=stylish -F=warn -v --ruleset=./.spectral.yaml
```
Running the previous version shows no errors:
```
npx @stoplight/spectral@5.8.1 lint reference/*.yml -f=stylish -F=warn -v --ruleset=./.spectral.yaml
```
the .circleci/.config.yaml was configured to run `npx @stoplight/spectral` without specifying a version – this results in the latest version being used. Specifying the version in the command to be `5.8.1` should fix and prevent updates to spectral causing build failures in the future.
=> Specify Spectral 5.8.1

reference/customers_v2.yml
There seems to be a bug in stoplight platform causing the export URL we use in stoplight next to 404 (ex: `https://bigcommerce.stoplight.io/api/v1/projects/bigcommerce/api-reference/nodes/reference/customers.v2.yml?branch=master&deref=all&format=json`). This results in the page not rendering when the site is built. I've noticed this happens sometimes when the filenames are too similar. Testing this theory with a copy of customers v2 with a slightly different name.
=> Fix Customers V2 404ing

reference/tax_classes.v2.yml
* Add created_at and updated_at response body changes, as introduced by SHIPPING-1013.
* Due to new date time column additions from SHIPPING-1013, documentation for tax_classes is out of date, and this PR is the fix for it.
=> feat(shipping): TAX-1014 Tax Class update

reference/catalog.v3.yml
Removed `price_list_id` query parameter from `GET  /catalog/products` and `GET  /catalog/products/{product_id}`.
See [PR 70074](https://github.com/bigcommerce/bigcommerce/pull/40074) for reference.
=> DEVDOCS-2660: Removed price_list_id query parameter

reference/catalog.v3.yml
`image_url` present in POST example, but not in schema for creating a product variant. Added `image_url` to schema. 
https://jira.bigcommerce.com/browse/DEVDOCS-2608
=> add image_url to POST /catalog/products/{product_id}/variants

reference/orders.v2.oas2.yml
Remove the following copy from the DELETE /orders/{order_id} API reference description:
> Any attempt to archive an order on a store with automatic tax enabled will fail, and will return `405 Method not allowed.`
The API Reference is out of date. The existing copy was introduced when orders could be deleted, however we introduced the ability to archive orders and it's currently possible to archive orders even when an automatic tax provider is enabled.
Ping: @uwikaiddi
=> docs(orders): DEVDOCS-2729 Update Orders v2 DELETE API Reference 

reference/tax_provider.yml
Updated **type** and **tax_exempt** field descriptions to also describe refund functionality.
Responding to developer feedback that the descriptions for these fields make no reference to refunds functionality.
Revert this PR.
ping @uwikaiddi @bigcommerce/orders @bigcommerce/shipping
=> docs(tax): Update tax exempt and type description

reference/tax.v3.yml
Change title link copy from:
> Get a Connection
To:
>Get Connection Status
Introducing language that better describes the functionality.
Revert this PR.
ping @uwikaiddi @bigcommerce/shipping
=> docs(tax): Change "Get a Connection" copy

reference/checkouts.sf.yml
This JIRA ticket https://jira.bigcommerce.com/browse/CHECKOUT-5767 requests documentation for developers who implement their own checkout and wants to know how AbandonedCart notification are triggered.
Also related to the discussion originated from this ticket: https://jira.bigcommerce.com/browse/CHECKOUT-5667
=> docs(checkout): CHECKOUT-5767 Adding an extra note to ensure developers understand the trigger point for AbandonedCart notification

reference/orders.v2.oas2.yml
Updated copy with API Reference for GET Order Shipping Addresses Quotes
Previous copy suggested that all shipping quotes presented to shopper in storefront are returned in the response, when in fact, only the shipping quotes that were selected and persisted are returned.
Ping: @aglensmith
=> Improve API Reference copy for GET Order Shipping Addresses Quotes 

reference/customers.v3.yml
##What
Add missing `postal_code` field to public documentation.
Bonus: removes `store_credit` field which should not have been there.
`postal_code` field was originally missed and has been added to the API.
ping @uwikaiddi @bigcommerce/dev-docs
=> docs(payment): Add postal_code to list stored instrument

reference/customers.v3.yml
[CUST-1566](https://jira.bigcommerce.com/browse/CUST-1566)
Updated the Example requests provided for the following endpoints:
- Customers Address POST:
1. Added an example for the `state_or_province` fixing the auto-generated value: `"string"`
2. Added an example for the `country_code` fixing the auto-generated value: `"string"`
3. Added an example for the `customer_id` fixing the auto-generated value: `0`
- Customers Address PUT:
1. Added an example for the `state_or_province` fixing the auto-generated value: `"string"`
2. Added an example for the `country_code` fixing the auto-generated value: `"string"`
3. Added an example for the `customer_id` fixing the auto-generated value: `0`
4. Added an example for the `id` fixing the auto-generated value: `0`
- Customers Consent PUT:
1. Fixed …
=> fix(customers): CUST-1566 Added examples for request bodies automatically created from schemas

reference/customers.v3.yml
[DEVDOCS-3011](https://jira.bigcommerce.com/browse/DEVDOCS-3011)
- Add a note to POST customers/addresses that body does not accept state or province codes
- update values in example to US address and fill in missing fields
- change the order of properties in 200 response to match the actual response format
- shorten example response body to only one customer instead of 5+
- remove required fields from POST description since info is also in the schema
- remove `required` flag from shared example since it doesn't apply
- create another shared response for customer address POST and PUT without meta, since that info is only present in GET responses
=> DEVDOCS-3011 Update POST Create a Customer Address info

reference/orders.v2.oas2.yml
DEVDOCS-3108
add new field "ip_address_v6" to Orders v2 API
Stoplight Studio:
- GET response: 
- PUT and POST payload:
=> DEVDOCS-3108 add new field "ip_address_v6" to Orders v2 API

reference/orders.sf.yml
Add new "consignments" field to Storefront Order API swagger.
The plan is we will only expose the "shipping" consignments after the experiment `ORDERS-4432.include_shipping_digital_pickup_consignments_in_storefront_order_api_response` fully ramped up.
example:
```
{
....
"consignments": {
"shipping": [
{
"lineItems": [
{
"id": 8
}
],
"shippingAddressId": 1,
"firstName": "first1",
"lastName": "last1",
"company": "company1",
"address1": "2802 Skyway Cir",
"address2": "Balcony",
"city": "Austin",
"stateOrProvince": "Texas",
"postalCode": "78704",
"country": "United States",
"countryCode": "US",
"email": "first1@bigcommerce.com",
"phone": "0410123452",
"itemsTotal": 1,
"itemsShipped": 0,
"shippingMethod": "Flat Rate",
"baseCost": 15.5,
"costExTax": 15.5,
"costIncTax": 16.7,
"costTax": 1.2, …
```
=> docs(orders): ORDERS-4505 add "consignments" field to Storefront Order API swagger

reference/tax_provider.yml
- Improve description of Sales Tax `name` field.
- Clarify that an empty name isn't a valid option.
- Improve language consistency for `human-readable`.
Context: Support case relating to the an empty Sales Tax name was raised via Avalara.
=> DEVDOCS-3389: Tax Provider API - Improve Sales Tax Name field description

reference/carts.sf.yml
As above
We created a while ago an endpoint `/cart/change-currency` to allow changing the currency of a cart on Storefront. However, we added it as a private endpoint so we didn't add the `storefront` namespace at the time.
Due to feedback from sales engineers and dev doc teams, it turns out developers would like to have public access to this endpoint in order to build custom solutions on the storefront that allows the shopper to change currency. 
In order to make this endpoint publicly available, we need to ensure the URL of the endpoint is consistent with other endpoints.
Revert
ping @bigcommerce/checkout  @bigcommerce/dev-docs @traci707
=> DEVDOCS-3302?: docs(checkout): CHECKOUT-6553 Add documentation for storefront cart currency endpoint

reference/settings.v3.yml
* removed `store_country` from store profile schema
=> DEVDOCS-3775 Continued - Remove store_profile

reference/customers.v3.yml
Remove customer_id field from the v3 PUT customer addresses endpoint request because it is completely ignored by the implementation but documented as a required field.
Before:
After:
=> DEVDOCS-3778: fix(customers): CUST-2064 Remove customer_id from update address

docs/storefront-graphql.md
* Remove request runner buttons/graphics
* Remove duplicate API info in intro
=> DEVDOCS-3670: broken image on graphql page

reference/customers.v3.yml
A follow up to the PR: https://github.com/bigcommerce/api-specs/pull/699
In the previous PR, form field schema was added to the request and response of the Customer Post endpoint. However the Customer Post general schema still had form fields missing from the address schema. This PR addresses that.
* form field schema was added to the address field under Customer Post
=> fix(customers): CUST-2101 Adding form field schema to address under Customer Post

reference/tax_provider.yml
Document our additive change to allow variable merchant calculation inputs for individual items, via our `tax_properties` field.
This change is already being used by one partner, Wine Direct, and successfully working with our third party tax provider Avalara. It should be safe to publish at any time.
Raised [DEVDOCS-3835](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3835) to describe this change.
ping @bigcommerce/shipping @bc-andreadao
=> docs(tax): DEVDOCS-3835 Add tax properties array to item requests

reference/abandoned_carts.v3.yml
Changed OAuth scopes to Information and Settings.
For Update Abandoned cart settings, they only work for permission modify of Information & settings
Fixed errors in file
=> DEVDOCS-3889: Updated-oauth-scopes

reference/redirects.v3.yml
The OAuth scopes for the Redirects API was incorrect and giving a 404 error. When changed to Content it worked. You can see the ticket for screenshots.
=> Devdocs 4059 update Oauth scope

reference/channels.v3.yml
* add bigcommerce platform to the list of storefront channel types
[DEVDOCS-4224]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4224 add bigcommerce platform to the list of storefront channel types

reference/orders.v2.oas2.yml
* Add `external_order_id` to `v2/orders`
@bigcommerce/orders
=> DEVDOCS-4325: add external_order_id to v2/orders

reference/tax_provider.yml
* Describing the logic around UPC vs SKU usage within the `ItemRequest` **item_code** field so that we have a higher level of self-service.
- A straight forward description update.
- Relates to feedback from a tax provider partner.
[DEVDOCS-4483]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
ping @bc-andreadao @bigcommerce/shipping
=> DEVDOCS-4483: [update description] Tax Provider, ItemRequest item_code

reference/tax_provider.yml
* Adding a missing description to ItemRequest.
* Since we have both ItemRequest and ItemRequestWrapping we need to make sure to remember to update both/keep both descriptions in sync.
ping @bigcommerce/shipping @bc-andreadao 
[DEVDOCS-4488]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4488: Tax Provider, include tax properties on ItemRequest

reference/orders.v2.oas2.yml
* Added `wrapping_id` to `orderCatalogProduct_Post` for v2 Orders
* Added descriptions to related wrapping fields to describe how to use them with `wrapping_id`
ORDERS ticket: https://bigcommercecloud.atlassian.net/browse/ORDERS-4969
* Added `wrapping_id` field to POST and PUT requests to `v2/orders` (currently only for Catalog Products). This allows existing gift wrapping options to be added to an order product when creating or updating via the v2 Orders API, bringing it closer to feature parity with CP.
* This is an additive change, so previous gift wrapping behaviour for POST and PUT remains the same and only changes when a request includes the `wrapping_id` field, such as requiring `wrapping_cost_inc_tax` and `wrapping_cost_ex_tax`.
* If a PUT request includes `wrapping_id` as `0` and …
=> DEVDOCS-4495 Orders V2 add wrapping_id to orderCatalogProductPost

reference/orders.v2.oas2.yml
1st commit: add "download consignment" support in PUT
2nd commit: correct "download consignment" structure in POST
1st commit: add "download consignment" support in PUT
2nd commit: correct "download consignment" structure in POST
- Engineer ticket: ORDERS-4836
- This branch is based on `DEVDOCS-4416` branch: https://github.com/bigcommerce/api-specs/tree/DEVDOCS-4416
ping @bigcommerce/orders 
[ORDERS-4836]: https://bigcommercecloud.atlassian.net/browse/ORDERS-4836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4528]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4528 download consignment support in PUT

reference/webhooks.v3.yml
I've added some missing error responses from the 'Get a Webhook' call (400, 401 and 404).
=> DEVDOCS-4544: [external] added additional responses for 'Get a Webhook' call

reference/orders.v2.oas2.yml
* Support for shipping consignment in PUT.
Related PRs: https://github.com/bigcommerce/bigcommerce/pull/48811
[DEVDOCS-4469]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(orders): DEVDOCS-4469: support shipping consignment in PUT.

reference/orders.v2.oas2.yml
Support gift certificate consignments in PUT /v2/orders
=> docs(orders) ORDERS-4981 support gift certificate consignment in PUT

reference/shipping_provider.yml
- Removes cart_id as a field as it is no longer there
- Adds some description to the request_context field to describe that uses the request context
Related branch
https://bigcommercecloud.atlassian.net/browse/SHIPPING-2535
@bigcommerce/shipping
=> SHIPPING-1607 altering the documentation after adding in the channel id

reference/catalog.v3.yml
PUT, POST to `v3/catalog/products` actually return `{"data": {}, "meta": {}}` and not `{"product_Full":{}, "meta":{}}` as stated in the specification.
Adjust field name in endpoint specification and example to match the actual behavior of the production API.
=> fixed wrong field names in v3/catalog/product

reference/price_lists.v3.yml
Get All Price List Records
Updating:
L.853 description: Returns a list of *Price List Records* associated with a *Price List*.
New value:
description: |-
Returns a list of *Price List Records* associated with a *Price List*.
**Notes**
* Up to 10 simultaneous GET requests are supported with this API. Running more than the allowed concurrent requests in parallel on the same store will result in a 429 status error and your additional requests will fail.
* In order to maximize performance, it is recommended to store Pricelist Records data to reduce number of calls.
* thing_that_changed
=> Adding Rate limit - "Get All Records" DEVOCS-4669

reference/price_lists.v3.yml
* Adding ParRateLimiting for getRecordsWithVariantId endpoint for documentation - https://developer.bigcommerce.com/api-reference/9eb908ec0a0fc-get-price-records-by-variant
Related to [1089](https://github.com/bigcommerce/api-specs/pull/1089/files)
Resource api-proxy: 
https://github.com/bigcommerce/api-proxy-java/blob/b1a8d820ffbfb17f45473f1b29760f38be3771d1/app/controllers/pricelists/PriceListRecordsController.scala#L98
[DEVDOCS-4669]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Adding Rate limits - DEVDOCS-4669

reference/customers.v3.yml
Adding max number of items in array to Create Customers - https://developer.bigcommerce.com/api-reference/1cea64e1d698e-create-customers Anything else?
https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4689
[DEVDOCS-4689]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4689 - Create Customer, add limit

reference/tax.v3.yml
Endpoints render on the api-tester. Only application/json content type is supported.
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4719: [migrate] Tax V3 API, rendering

reference/tax.v3.yml, reference/tax_classes.v2.yml, reference/tax_properties.v3.yml
- Move examples for taxes so they render
- Removed unneeded example that doesn't render
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4719: [migrate] Tax APIs 

reference/tax_settings.v3.yml
Update the `tax_settings` documentation  with a new field `should_subtract_store_tax`
This will allow the merchants to both read and set the new `should_subtract_store_tax` via the bigcommerce public API
PR: https://github.com/bigcommerce/bigcommerce/pull/52265
JIRA Ticket: https://bigcommercecloud.atlassian.net/browse/TAX-1421
JIRA Ticket: https://github.com/bigcommerce/bigcommerce/pull/52265
(naming change from `tax_should_unwind_store_tax` -> `should_subtract_store_tax`)
ping @bigcommerce/shipping @bc-andreadao @bigcommerce/devdocs-codeowners 
[DEVDOCS-4783]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(tax): DEVDOCS-4783 Introduce should subtract store tax

reference/tax.v3.yml
When a client attempts to disconnect a tax provider that is not connected to the store, it now throws a 404 error and notifies the client that they are trying to disconnect a tax provider that does not exist.
Code change: https://github.com/bigcommerce/bigcommerce/pull/52321
ping @bigcommerce/shipping  @bc-andreadao @bigcommerce/devdocs-codeowners
=> DEVDOCS-4931: [update] Tax Connection API, edit 404 error message

reference/catalog.v3.yml, reference/catalog/categories_catalog.v3.yml, reference/catalog/category-trees_catalog.v3.yml
According to the APi response, the `url` property should be `custom_url` for Category Model
=> Rename `url` to `custom_url` in Category Model

reference/orders.v2.oas2.yml
Add support for the following query parameters
* `include=consignment` in  `GET /v2/orders/{{order_id}}`
* `include=consignment.line_items` in `GET /v2/orders/{{order_id}}/consignments`
```
> spectral lint  reference/orders.v2.oas2.yml
No results with a severity of 'error' found!
```
* https://github.com/bigcommerce/bigcommerce/pull/53387
ping @bc-tgomez  @bigcommerce/team-orders 
[DEVDOCS-5230]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5230 /v2/orders support include of consignments and consignments.line_items

reference/orders.v2.oas2.yml
* Follow on from https://github.com/bigcommerce/api-specs/pull/1380#issue-1808646440 to also add the relevant `include` to `GET /v2/orders` and `POST`
ping @bc-tgomez 
[DEVDOCS-5230]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-5230 Add includes for GET all Orders and Create Order

reference/orders.v2.oas2.yml
No Dev Docs ticket.
This was created and done adhoc under the ticket name SHIPPING-700.
- Include `tracking_link` information as part of the `orderShipment_post request`. Tracking links were already a feature, but this was not documented.
- Update the carrier list for the `shipping_provider` field. In addition to our native providers we also support carriers created through the Shipping Provider API.
- Style changes auto-fixed by the IDE.
ping @bigcommerce/team-orders @bigcommerce/team-shipping @bc-andreadao @bc-tgomez
=> Update orders/v2/shipments documentation

reference/orders.v2.oas2.yml
No Dev Docs ticket.
This doc task acts as a follow on from the work done in [SHIPPING-2792](https://bigcommercecloud.atlassian.net/browse/SHIPPING-2792) (which adds the new API property of  `generated_tracking_link` to the shipments API).
* Include `generated_tracking_link` property as part of our API responses to the order/shipments API
* Update examples to show how the `generated_tracking_link` is presented to the API client.
* Update usage description on how to use this 
If interested, here is the [PR](https://github.com/bigcommerce/bigcommerce/pull/54299) that adds this feature
ping @bigcommerce/team-orders @bigcommerce/team-shipping @bc-tgomez @donald-nguyen-bc 
[SHIPPING-2792]: https://bigcommercecloud.atlassian.net/browse/SHIPPING-2792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
=> [SHIPPING-2792]: [revise] Ordersv2, Update tracking_link details

reference/orders.v2.oas2.yml
ORDERS-5912
Add new `discounted_total_inc_tax` field for the API response of get order product.
This functionality was provided through https://bigcommercecloud.atlassian.net/browse/ORDERS-5592 and https://bigcommercecloud.atlassian.net/browse/ORDERS-5911.
ping @bigcommerce/team-orders @bigcommerce/dev-docs-team
=> docs(orders): ORDERS-5912 Expose discounted_total_inc_tax on the orders v2 api

reference/catalog/products_catalog.v3.yml
Already defined on the endpoint level.
* remove duplicate video id param from product video endpoint
ping {names}
=> bugfix: remove duplicate video id param on product video endpoint

reference/themes.v3.yml
Already defined at endpoint level.
* remove duplicate uuid param on theme configuration endpoint
ping {names}
=> bugfix: remove duplicate uuid param on theme configuration endpoint.

reference/catalog/categories_catalog.v3.yml
category_id is already specified as a param on an endpoint level and is not required on method level also.
* remove duplicate category id para on category sort order endpoint
ping {names}
=> bugfix: remove duplicate category id param on category sort order endpoint

reference/catalog/products_catalog.v3.yml
param is already defined on endpoint level, not required on a method level as well.
* remove duplicate review id param on product reviews endpoint
ping {names}
=> bugfix: review duplicate review id param on product reviews endpoint

reference/catalog/product-variants_catalog.v3.yml
These are already defined on the endpoint level and aren't required on the method level.
* remove duplicate variant_id from product variants endpoint
ping {names}
=> bugfix: remove duplicate variant_id param from product variants endpoint

reference/catalog/product-variant-options_catalog.v3.yml
Use definition on endpoint level and remove those on a method level.
* remove duplicate option_id param from product variant options endpoint 
ping {names}
=> bugfix: remove product variant options option_id param

reference/catalog/product-modifiers_catalog.v3.yml
Already defined on endpoint level, not required on the method level.
* remove duplicate modifier_id param from product modifier endpoint
ping {names}
=> bugfix: remove duplicate product modifier id param

reference/catalog/product-variants_catalog.v3.yml
metafield_id and variant_id params only need to be defined at endpoint level. Method level definitions are duplicates.
9dc1-14ac0ee94847)
* remove duplicate metafield_id and variant_id param definitions on variant metafields endpoint
ping {names}
=> bugfix: remove duplicate variant metafield and variant id params.

reference/catalog/products_catalog.v3.yml
Parameter defined on both the endpoint and method level.
* remove duplicate metafield_id param on product metafield endpoint
ping {names}
=> bugfix: remove duplicate metafield_id param definition on product metafield endpoint

reference/catalog/brands_catalog.v3.yml
Already defined on the endpoint level. Not required on the method level as well
* remove duplicate `brand_id` param definition on brand metafield endpoint
ping {names}
=> bugfix: remove duplicate brand_id param on brand metafield endpoints.

reference/catalog/categories_catalog.v3.yml
category_id param is already defined as a parameter on an endpoint, it is not needed on the method level as well.
* remove duplicate `category_id` param definition on the category image endpoint
ping {names}
=> bugfix: remove duplicate category_id on category image endpoint

reference/catalog/brands_catalog.v3.yml
brand_id param is already defined on an endpoint level and is not required on the method level.
* remove duplicate brand_id param on brand image endpoint
ping {names}
=> bugfix: remove duplicate brand_id param on brand image endpoint

reference/catalog/products_catalog.v3.yml
It is already defined on an endpoint level and is not required on a method level.
* remove duplicate custom field id param.
ping {names}
=> bugfix: remove duplicate custom field id param.

reference/customers.v3.yml
It is already defined on the endpoint, it does not need to be defined on each method
* remove duplicate customer_id param definition on customer consent endpoint
ping {names}
=> bugfix: remove duplicate customer id param on consent endpoint.

reference/catalog/products_catalog.v3.yml
Remove duplicate complex rule ID param on method level when already defined on endpoint level
* remove duplicate complex rule ID path param definition
ping {names}
=> bugfix: remove duplicate complex rule id path params

reference/catalog/categories_catalog.v3.yml
These are already defined on an endpoint level and then re-defined on a method level which causes duplication in the api docs.
* remove duplicate category_id and metafield_id path parameter definitions
ping {names}
=> bugfix: remove duplicate category id and metafield id params.

reference/catalog/products_catalog.v3.yml
remove duplicate bulk pricing rule id param definition.
Parameter is already defined on the endpoint and is being redefined on the method level
*  remove duplicate bulk pricing rule id param definition
ping {names}
=> bugfix: remove duplicate bulk pricing rule id param definition

reference/catalog/brands_catalog.v3.yml
brand id param is defined on the endpoint but duplicate definitions are also on the method level definitions.
* removed duplicate brand id param definitions
ping {names}
=> bugfix: remove duplicate brand id params

reference/settings.v3.yml
Remove duplicate Web Analytics ID path param definition. 
Defined on endpoint but redeclared on individual methods.
* remove duplicate web analytics ID param definitions 
ping {names}
=> bugfix: remove duplicate web analytics id param.

reference/catalog/products_catalog.v3.yml
The image ID path parameter on the product image endpoint is defined at the endpoint level and on the method level in multiple places. 
This leads to duplicate params in the doc output. Remove duplicates.
* remove duplicate image id path parameters on product image endpoint
ping {names}
=> bugfix: remove duplicate image id path parameters

reference/carts.v3.yml
* Include the gift_wrapping structure and a sample in the v3/cart response
ping @bigcommerce/dev-docs @bigcommerce/team-checkout 
[CHECKOUT-7716]: https://bigcommercecloud.atlassian.net/browse/CHECKOUT-7716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(checkout): CHECKOUT-7716 Include the gift_wrapping structure and a sample in the v3/cart response

reference/orders.v2.oas2.yml
The OpenAPI parser was unable to comprehend the escaping approach of this example on an orders endpoint. I've modified it to use single quotes so that the double quotes don't need to be escaped. 
* change escaping of orders example for improved ability to parse.
ping {names}
=> [external] bugfix: fix escaping in orders

reference/redirects.v3.yml
n/a
- Added `id` as a sortable field in the V3 Redirects API
https://bigcommercecloud.atlassian.net/browse/STRF-11308
ping @bigcommerce/dev-docs
=> STRF-11308: Add "id" as a sortable field to V3 redirects

reference/redirects.v3.yml
* Add `include_dynamic_target_urls` as an optional boolean to the V3 Redirect Import/Export Create Export request body
* Update CSV structure examples to account for the updated structure
- Depends on this PR being merged: https://github.com/bigcommerce/redirect-import-export/pull/53
- https://bigcommercecloud.atlassian.net/browse/STRF-11315
ping @bigcommerce/dev-docs
=> STRF-11315: Add "include_dynamic_target_urls" boolean to Redirect Im/Ex Create Export request body

reference/catalog/products_catalog.v3.yml, reference/customers.v3.yml, reference/orders.sf.yml, reference/price_lists.v3.yml
_For context, this PR originated from: https://github.com/matthewvolk/bigrequest/issues/84 as a solution for inconsistent Typescript type definitions being generated from our OpenAPI spec files. I haven't checked if these changes introduce any unintended side effects to other ways our spec files are consumed!_
- Refactors the schema definition of the `include` query parameter across various API endpoints to indicate that `include` accepts a comma-separated list of enum values, rather than one-of an enum value. 
- A schema with `type: string` and `enum: [value1,value2]` resolves to: `?include=[value1|value2]` (_either_ `value1` _or_ `value2`) ([source: swagger.io](https://swagger.io/docs/specification/data-models/enums/))
- If we instead describe the schema as a `type: array`, where the …
=> (no ticket): [revise] query param include should accept comma separated list of values

reference/abandoned_carts.v3.yml
The `channel_id` param is defined on a method level as well as an endpoint level. Remove it from the method level
* remove duplicate `channel_id` on abandoned cart settings endpoint.  
ping {names}
=> (external): [update] Abandoned Carts, remove duplicate channel_id param

reference/customers.v2.yml
The update customer API does not have any required fields. It is incorrectly documented in the API spec and on the website.
* Removed the required fields for the update customer API (the customer_Put model)
* Moved the customer_Put model under the schema definations
N/A
[DEVDOCS-4878]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEVDOCS-4878: [external] Customers V2, remove required fields
