- reference/orders.sf.yml
- removed data and meta objects
- updated Order definition
> DEVDOCS-2316: Removed data and meta, updated Order definition

- reference/marketing.v2.yml
Updated requests and response definitions and examples for purchase_date parameter.
> DEVDOCS-2323: Updated definition and examples for purchase_date parameter

- reference/channels.v3.yml
DEVDOCS-2263: Changed the definition for Update Channel Listings endpoint
> DEVDOCS-2363: update description for updating channel listing

- reference/catalog.v3.yml
DEVDOCS-2365: Removed price_list_id param from Catalog Get a Product endpoint
> DEVDOCS-2365: Removed price_list_id

- reference/price_lists.v3.yml
- Improve verbiage of Price List Batch Upsert endpoint documentation
- Correct a few inaccuracies
> Fix price list docs

- reference/widgets.v3.yml
- added create_new_version property to widget template schema for PUT 
- updated code example
> DEVDOCS-2395: Added create_new_version property 

- reference/carts.v3.yml
Matt Hill suggested that I add the option of using a timestamp or a date array. I added this as a comment in the code.
In addition, I added a description for this example.  I also needed to fix the spacing
> Devdocs 2407 add comment for option value carts.v3

- reference/orders.v2.oas2.yml
- removed the "required" tag from "products" 
- deleted the text "required : products, billing_address"
> DEVDOCS-2416: Updated Orders V2

- reference/orders.v2.oas2.yml
Updated currency fields' definitions in schema and API Overview.
> DEVDOCS-2284: Updated currency fields' definitions

- reference/widgets.v3.yml
Added storefront_api_query to widget template schema
> DEVDOCS-2213: Added storefront_api_query to widget template schema

- reference/widgets.v3.yml
Added storefront_api_query to widgetTemplate_Base
> Devdocs-2213: add storefront api query

- reference/wishlists.v3.yml
Updated definitions in PUT /wishlists/{wishlist_id}
> Updated definitions

- reference/checkouts.v3.yml
Fix address2 and company example values in checkout V3 API
> Fix address2 and company example values in checkout V3 API

- reference/settings.v3.yml
Changed 204 error to 200 for DELETE
> Updated Error Code

- reference/catalog.v3.yml
[DEVDOCS-2464](https://jira.bigcommerce.com/browse/DEVDOCS-2464)
Added in "multipart/form-data media type" and supported image types for image-file
> image_file_DEVDOCS-2464_Final

- reference/carts.sf.yml
[DEVDOCS-2474](https://jira.bigcommerce.com/browse/DEVDOCS-2474)
Updated definition for listPrice
> updated listPrice definition

- reference/catalog.v3.yml
[DEVDOCS-2464](https://github.com/bigcommerce/api-specs/pull/105)
I noticed that I needed to remove an extra line.
> Fix editorial errors

- reference/channels.v3.yml
- Added query params and updated definitions for GET /channels
- Removed `archived` status
> DEVDOCS-2492: Updated filters for Channels API

- reference/webhooks.v3.yml
> Add Webhooks v3

- reference/price_lists.v3.yml
Updated overview per [PR 116](https://github.com/bigcommerce/api-specs/pull/116)
> Updated overview

- reference/checkouts.sf.yml
- reference/orders.sf.yml
[DEVDOCS-2507](https://jira.bigcommerce.com/browse/DEVDOCS-2507)
Added giftWrappingCostTotal to checkout storefront and orders storefront spec files.
> Devdocs 2507 added gift wrapping cost total field

- reference/catalog.v3.yml
> Updated filter order

- reference/themes.v3.yml
- Added filters
- Set endpoint to public
> DEVDOCS-2503: Update filters

- reference/catalog.v3.yml
Updated 409, 413, and 422 error schemas for Update Products (bulk).
> DEVDOCS-2473: Update Product Resp Errors

- reference/settings.v3.yml
- updated examples
- added missing properties
> DEVDOCS-2477: Update Settings API

- reference/catalog.v3.yml
> DEVDOCS-2517: Update Product Image Types

- reference/carts.v3.yml
[DEVDOCS-2519](https://jira.bigcommerce.com/browse/DEVDOCS-2519)
Did some cleaning up while in the file.
> Modified reference/carts.v3.yml

- reference/.spectral.yml
- reference/orders.v2.oas2.yml
Resolves some specification linting errors and adds stoplight's spectral rule set config file.
> Fix Errors in Orders V2

- docs/available-apis.md
- removed Deprecations and sunsets section
- linked to Deprecations and Sunsets page in resources
> DEVDOCS-2487: Removed deprecations section, added resources.

- reference/orders.sf.yml
* Added Channel ID
* Fixed Some Linting Errors
> DEVDOCS-2566: Add Channel ID

- reference/carts.sf.yml
- Added schema details for `optionSelections` on Storefront Cart API - Create Cart [#95]
> Added optionSelections to Storefront Cart API - Create Cart

- reference/checkouts.sf.yml
- reference/checkouts.v3.yml
[DEVDOCS-2479](https://jira.bigcommerce.com/browse/DEVDOCS-2479)
A list of inconsistencies was added to this ticket.  This PR contains changes to fix inconsistencies listed in the ticket.
> DEVDOCS-2479-updates to checkout

- reference/orders.v2.oas2.yml
[DEVDOCS-2572](https://jira.bigcommerce.com/browse/DEVDOCS-2572)
Added note so users know that the zip code is a required field in the billing address.
> add_note_for_zip_code/orders.v2.oas2.yml

- .github/workflows/main.yml
Adds Stoplight Spectral Action for linting.
> Add Spectral Action

- reference/carts.sf.yml
- reference/carts.v3.yml
- reference/catalog.v3.yml
- reference/checkouts.sf.yml
- reference/checkouts.v3.yml
- reference/customers.v2.yml
- reference/customers.v3.yml
- reference/marketing.v2.yml
- reference/orders.v2.oas2.yml
- reference/store_content.v2.yml
- reference/store_information.v2.yml
- reference/subscribers.v3.yml
- changed the example email we use in our docs to an @example.com address
> replace email.com with example.com

- models/themes/theme_objects.yml
[DEVDOCS-2559](https://jira.bigcommerce.com/browse/DEVDOCS-2559)
> Devdocs 2559 image manager

- reference/checkouts.sf.yml
- reference/checkouts.v3.yml
Updated query params per [DEVDOCS-2581](https://jira.bigcommerce.com/browse/DEVDOCS-2581) and [DEVDOCS-2582](https://jira.bigcommerce.com/browse/DEVDOCS-2582).
> Update Checkout query params

- reference/catalog.v3.yml
* Renamed Product Options to Product Variant Options
* Renamed Product Option Values to Product Variant Option Values
> DEVDOCS-2570: Updated tags and names of operations

- reference/carts.v3.yml
@valentindellangela Can you please add your review?
> DEVDOCS-2571: Added a note about option_value

- models/themes/theme_objects.yml
[DEVDOCS-2623](https://jira.bigcommerce.com/browse/DEVDOCS-2623)
> Devdocs 2624 and 2623 checkout customer model

- reference/catalog.v3.yml
- updated DELETE operation definition
- updated GET and DELETE filters
> DEVDOCS-2653: Updated catalog categories

- reference/marketing.v2.yml
- Updated PUT example
- Removed "Required" note
- Updated "Read Only" note
> DEVDOCS-2652: Updated definition

- reference/customers.sf.yml
Added the following to customers.sf.yml
x-stoplight:
docs:
includeDownloadLink: false
showModels: false
> added_customers.sf

- reference/shipping.v3.yml
[DEVDOCS-2609](https://jira.bigcommerce.com/browse/DEVDOCS-2609)
I fixed a typo and updated the example to correct the brackets.
> Fixed typo shipping.v3.yml

- reference/catalog.v3.yml
- added `mpn` to `productVariant_Base`
- updated examples
> Added the mpn property

- reference/checkouts.v3.yml
Removing the empty lines left after implementing [DEVDOCS-2656](https://jira.bigcommerce.com/browse/DEVDOCS-2656)
> remove-empty-lines-checkouts.v3.yml

- reference/payment_processing.yml
[DEVDOCS-2605](https://jira.bigcommerce.com/browse/DEVDOCS-2605)
The headers looked correct, so I did not change them.
X-Auth-Token  ACCESS_TOKEN   api.bigcommerce.com
Authorization  PAYMENT_ACCESS_TOKEN payments.bigcommerce.com
Updated the following:
Get Accepted Payment Methods: Updated the Response example to match the structure of the Schema.
Process Payment: Updated the Request Body, removed amount and currency_code fields.
> payment_methods_and_payment_processing.yml

- reference/checkouts.sf.yml
[DEVDOCS-2725](https://jira.bigcommerce.com/browse/DEVDOCS-2725)
Fixed StateOrProvinceCode
> fix-errors-checkouts.sf.yml

- reference/customers.v3.yml
Updating the public facing Customer API docs with the new V3 ValidateCredentials endpoint we created - captured in this ticket https://jira.bigcommerce.com/browse/CUST-1424.
Swagger Editor
cc @bigcommerce/dev-docs @bigcommerce/checkout
> feat(checkout): CUST-1460 Add documentation for the new V3 ValidateCredentials endpoint

- reference/carts.v3.yml
[DEVDOCS-2701](https://jira.bigcommerce.com/browse/DEVDOCS-2701)
> Devdocs 2701 add settings msf carts.v3.yml

- reference/carts.v3.yml
Cleaning up headings in the cart file
> Cleaning_up_headings/carts.v3.yml

- reference/carts.v3.yml
This reverts commit 712ff9b42937571b58d253072235dff13fb9d804.
> Revert "Cleaning_up_headings/carts.v3.yml (#288)"

- reference/channels.v3.yml
[CHP-6988](https://jira.bigcommerce.com/browse/CHP-6988)
> CHP-6988: Fix and update channels public API swagger

- reference/catalog.v3.yml
[DEVDOCS-2905](https://jira.bigcommerce.com/browse/DEVDOCS-2905)
Moved changes to this PR.
> Changes-for-DEVDOCS-2905-catalog.v3.yml

- reference/carts.v3.yml
- reference/checkouts.v3.yml
Main Jira ticket: https://jira.bigcommerce.com/browse/CHECKOUT-5069
API update ticket: 
- https://jira.bigcommerce.com/browse/CHECKOUT-6241
- https://jira.bigcommerce.com/browse/CHECKOUT-6242
Document update Ticket: https://jira.bigcommerce.com/browse/CHECKOUT-6253
@bigcommerce/checkout @bigcommerce/dev-docs
> docs(checkout): CHECKOUT-6253 Introducing promotion field for the API reference document for Carts and Checkout

- reference/orders.v3.yml
Updating doc as transaction journal is added for all the providers
https://github.com/bigcommerce/api-specs/pull/646
https://github.com/bigcommerce/api-specs-ssot/pull/43
https://github.com/bigcommerce/api-beta-msf/pull/1
> DEVDOCS-3610: (PAYMENTS-7720) Updating doc as transaction journal is added for all the providers

- reference/shipping.v3.yml
[DEVDOCS-3557](https://jira.bigcommerce.com/browse/DEVDOCS-3557)
Changes for shipping api docs were merged to DEVDOCS-3557 in [PR 626](https://github.com/bigcommerce/api-specs/pull/626). These changes now need to merged to master branch.
> DEVDOCS-3557 fix(shipping): SHIPPING-700 Update Customs Info API docs 

- reference/catalog.v3.yml
- reference/store_content.v2.yml
[DEVDOCS-3576](https://jira.bigcommerce.com/browse/DEVDOCS-3576)
> Devdocs 3576 blog reference

- reference/orders.v2.oas2.yml
This is the doc change for those changes made in these 2 PRs: [#1](https://github.com/bigcommerce/bigcommerce/pull/45470) and [#2](https://github.com/bigcommerce/bigcommerce/pull/45512).
**1. Simplify the response payload of GET requests:**
**1.1. simplify the response payload of `GET /v2/orders/{order_id}/consignments`**
Before change:
```
[
{
"id": 2,
"line_items": {
"url": "https://api-proxy.service.bcdev/stores/acku7y1wo0/v2/orders/101/products",
"resource": "/orders/101/products"
},
"fulfillment_method": {
"pickup": {
"pickup_method_id": 1,
"pickup_method_display_name": "Pickup Method 1.1",
"collection_instructions": "Pickup Method 1.1 instructions",
"collection_time_description": "Pickup Method 1.1 time",
"location": {
"id": 1,
"name": "Location 1",
"code": "BC-LOCATION-1", …
```
> docs(orders): ORDERS-4621 Simplify consignments payload in /v2/orders

- reference/catalog.v3.yml
- reference/checkouts.sf.yml
- reference/checkouts.v3.yml
- reference/pricing.sf.yml
- reference/store_content.v2.yml
Co-authored-by: Mark Murphy <mark.murphy@bigcommerce.com>
> Corrected type of method called on endpoint (#656)

- reference/checkouts.sf.yml
- reference/orders.v3.yml
* remove duplicate x-internal tags
* return Storefront Carts to sidebar
> DEVDOCS-3699: remove duplicate x-internal tags

- reference/checkouts.sf.yml
- reference/customers.v3.yml
- reference/orders.v2.oas2.yml
Merge Staging changes into Master. No broken links found.
> Merge Staging into Master

- reference/settings.v3.yml
> Devdocs 3732

- reference/channels.v3.yml
https://jira.bigcommerce.com/browse/DEVDOCS-3419
> DEVDOCS-3419 

- .stoplight.json
* Add PR templates to `.stoplight.json`
> Add PR templates to `.stoplight.json`

- reference/payment_processing.yml
* Corrected path typo per ticket. Minor additional corrections.
> DEVDOCS-3786: fix payment processing paths

- reference/catalog.v3.yml
No devdoc ticket
Fixed file errors
> Fixed-file-errors

- reference/catalog.v3.yml
`value`  cannot be edited unless using the owner's credentials, therefore added it with the others.
> Devdocs 3784 add value to list

- reference/carts.sf.yml
- reference/catalog.v3.yml
* [DEVDOCS-3784](https://jira.bigcommerce.com/browse/DEVDOCS-3784) - #723 - @traci707 
* [DEVDOCS-3718](https://jira.bigcommerce.com/browse/DEVDOCS-3718) - #725 - @traci707 
* [DEVDOCS-3302](https://jira.bigcommerce.com/browse/DEVDOCS-3302) - #727 - @traci707 
* no ticket: resolve catalog spec file errors - #728  - @traci707 
Indicate when done.
* ~~Check links with tool~~ -- @slsriehl -- **done**, a lot of changes
* ~~Check ToC~~ -- @slsriehl -- **done**, one hundred billion changes
* Add redirects if needed -- TBD
* this is a lot of work. don't merge until discussed. :(
> Staging into master

- reference/checkouts.v3.yml
Added new endpoint, v3/checkouts/{checkoutId}/discounts
> DEVDOCS-3762: add-discount-to-checkout

- reference/webhooks.v3.yml
* Updated ref file
* Added Webhook Admin and Events
> DEVDOCS-2640: Webhook Admin and Events

- reference/checkouts.v3.yml
* fixed so X-Auth-Token param showed up
* add endpoint tag so it has its own section
> Fix security param

- reference/checkouts.v3.yml
> Added Checkout tag

- reference/checkouts.v3.yml
Added an example using the webdav: prefix
> DEVDOCS-3781: add-webdav-example

- models/webhooks/webhooks_events.yml
- reference/abandoned_cart_emails.v3.yaml
- reference/abandoned_carts.v3.yml
- reference/carts.v3.yml
- reference/catalog.v3.yml
- reference/channels.v3.yml
- reference/checkouts.v3.yml
- reference/custom-template-associations.v3.yml
- reference/customers.v2.yml
- reference/customers.v3.yml
- reference/email_templates.v3.yml
- reference/geography.v2.yml
- reference/orders.v2.oas2.yml
- reference/payment_methods.v2.yml
- reference/payment_processing.yml
- reference/price_lists.v3.yml
- reference/redirects.v3.yml
- reference/scripts.v3.yml
- reference/shipping.v2.yml
- reference/shipping.v3.yml
- reference/store_content.v2.yml
- reference/store_information.v2.yml
- reference/storefront_tokens.v3.yml
- reference/subscribers.v3.yml
- reference/tax.v3.yml
- reference/tax_classes.v2.yml
- reference/themes.v3.yml
- reference/webhooks.v3.yml
- reference/widgets.v3.yml
- reference/wishlists.v3.yml
* find and replace $$.env.store_hash with store_hash
> DEVDOCS-3729 - find and replace $$.env.store_hash with store_hash

- reference/carts.v3.yml
- reference/channels.v3.yml
- reference/checkouts.v3.yml
- reference/orders.v2.oas2.yml
- reference/redirects.v3.yml
- reference/settings.v3.yml
- reference/store_content.v2.yml
- reference/store_information.v2.yml
> Staging to Master

- reference/orders.v3.yml
> Devdocs 4175 fork

- reference/checkouts.v3.yml
* Add `custom_checkout_supports_uco_settings` to v3/checkout/settings API endpoint
Ping @bigcommerce/checkout @bigcommerce/dev-docs
> DEVDOCS-4252: docs(checkout): CHECKOUT-6736 Add custom_checkout_supports_uco_settings to v3/checkout/settings API endpoint

- reference/current_customer.yml
> DEVDOCS-3950: Converting to OAS3

- reference/channels.v3.yml
* Add channel metafield endpoints
> DEVDOCS-4100 Document channel metafields APIs

- reference/catalog.v3.yml
[DEVDOCS-3728]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-3728 updates to createupdate categories batch api documentation

- reference/tax_properties.v3.yml
-Converted Tax Properties yml spec to OAS3. 
-Note: base branch for this PR is DEVDOCS-4006-tax-properties
> DEVDOCS-4354 convert oas3

- reference/tax_properties.v3.yml
- toc.json
-Merge on GA date
This PR is related to [PR 1533](https://github.com/bigcommerce/dev-docs/pull/1533) (the corresponding API doc for this API spec) and [PR 108](https://github.com/bigcommerce-labs/next-dev-center-prototype/pull/108) (redirects)
> Devdocs 4006 tax properties

- reference/tax_provider.yml
-Move changes from PR #536 to staging 
-Don't merge until GA date
> DEVDOCS-3835 update tax provider api spec with tax properties

- reference/orders.v3.yml
Co-authored-by: ansnaldo <34357510+ansnaldo@users.noreply.github.com>
Co-authored-by: Tomas Gerulaitis <tomas.gerulaitis@space48.com>
* Change validation to oneOf from anyOf
> DEVDOCS-4184: [edit] Fix the request body schema for creating refunds

- reference/customers.v3.yml
Co-authored-by: Traci Porter <traci.porter@bigcommerce.com>
* Add Customer Segmentation  and Shopper Profile IDs
> chore(customers): (Customer Segmentation) CUST-1745 add includes for segments (#895)

- reference/customers.v3.yml
* see following PRs
* #895 
* #943 
* #962 
[DEVDOCS-4368]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-4368: [add] Customers API, add includes for segments

- reference/orders.v2.oas2.yml
* Add documentation or v2 Orders POST with a downloads consignment.
* [ORDERS-4833]
* See #949 
[DEVDOCS-4416]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ORDERS-4833]: https://bigcommercecloud.atlassian.net/browse/ORDERS-4833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> doc(orders): ORDERS-4833 download consignments

- reference/orders.v2.oas2.yml
* thing_that_changed
@bc-tgomez
> DEVDOCS - 4416 add missing schema shippingQuotesConsignment_Resource

- reference/tax_provider.yml
Merge to staging 
[DEVDOCS-4483]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-4483: [maintenance] Adjust Tax Provider ItemRequest Item Code description

- models/email_templates/_all.yml
* Modified models/email_templates/_all.yml
[DEVDOCS-4506]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-4506 [maint] Rename "Return Approved" email into "Return Requested"

- pull_request_template.md
- pull_request_template_CODEOWNER.md
- reference/customers.v3.yml
- reference/orders.v2.oas2.yml
- reference/tax_provider.yml
- toc.json
[DEVDOCS-4511]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Devdocs 4511 alt

- models/email_templates/abandoned_cart_email.yml
Moved the deprecated schema down so you see the current schema first
[DEVDOCS-4530]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-4530: [edit] Abandoned Carts, move deprecated schema

- reference/tax_classes.v2.yml
Changed examples for date-time (reflect format I get from testing). SME approval from [PR 985](https://github.com/bigcommerce/api-specs/pull/985#discussion_r978286629)
[DEVDOCS-4508]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-4508 date format

- reference/channels.v3.yml
Updated the menu paths for multi-storefront
[DEVDOCS-4036]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Devdocs 4036 menu paths

- reference/abandoned_carts.v3.yml
- reference/currencies.v2.yml
- reference/current_customer.yml
- reference/form_fields.sf.yml
- reference/marketing.v2.yml
- reference/payment_methods.v2.yml
- reference/shipping.v2.yml
- reference/subscriptions.sf.yml
> (no ticket): [update] Clean up linting errors

- reference/checkouts.v3.yml
* Introduce tax_included field of cart field for V3 checkout endpoint
Ping @bigcommerce/checkout @bigcommerce/dev-docs
> docs(checkout): CHECKOUT-7093 Introduce tax_included field of cart field for V3 checkout endpoint

- reference/catalog.v3.yml
Moved channels to appear after categories
[DEVDOCS-3840]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-3840: [update] Catalog, move channels after categories

- .eslintrc.json
- .github/workflows/lint.yml
- .gitignore
- package-lock.json
- package.json
> (no ticket): [tools] MDX linter, create + add github action

- reference/shipping_provider.yml
Move response example for Request Rates endpoint so that it will render
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEVDOCS-4719: [migrate] Shipping provider API, move example

- reference/orders.v2.oas2.yml
* Add "form_fields" to request payload for: 
- PUT /v2/orders/{order_id} :
```
{
"billing_address": {
"form_fields": [
{
"name": "picklist1",
"value": "picklist-value-2"
},
{
"name": "textfield1",
"value": "text2"
},
{
"name": "radio1",
"value": "radio-value-2"
},
{
"name": "checkbox1",
"value": [
"checkbox-value-2"
]
},
{
"name": "multilinetextfield1",
"value": "line1\nline2"
},
{
"name": "numberonlyfield1",
"value": 123.2
},
{
"name": "passwordfield1",
"value": "password2"
}
]
},
"shipping_addresses": [
{
"id": 23,
"form_fields": [
{
"name": "picklist1",
"value": "picklist-value-3"
}
]
}
]
}
```
- PUT /v2/orders/{order_id}/shipping_addresses/{id} :
```
{
"form_fields": [
{
"name": "picklist1",
"value": "picklist-value-3"
}
]
}
```
More examples in the implementation PRs:
- Support …
> docs(orders): DEVDOCS-4800 allow updating billing address & shipping address custom form fields in Orders v2 API

- reference/checkouts.sf.yml
- reference/checkouts.v3.yml
- reference/orders.v2.oas2.yml
- [DEVDOCS-4651]
[DEVDOCS-4651]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Staging to Main

- reference/orders.v2.oas2.yml
[DEVDOCS-4893](https://jira.bigcommerce.com/browse/DEVDOCS-4893)
**What changed:**
- Update OrdersV2 API and delete all requests to support limit parameters
**Related PRs:**
* https://github.com/bigcommerce/api-specs/pull/1276
> DEVDOCS-4893: [update] Ordersv2, delete all request to support limit param

- reference/marketing.v2.yml
* Remove invalid Coupon property `restricted_to`
ping {names}
> (external): [update] Marketing V2, remove invalid str property in restricted_to

- reference/redirects.v3.yml
https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3978
Add the Redirect Import/Export V3 endpoints to the Redirects swagger documentation.
https://bigcommercecloud.atlassian.net/browse/PROJECT-3843
[DEVDOCS-3978]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> STRF-11160: [new] Redirects V3, add Import-Export
